### ISSUE TITLE
Support for piping

### ISSUE THREAD

**Issue by ajeebkp23** [clobrano/raffaello#1]
Hi, I found rafaello highly useful. But one question? Is it possible to use with pipe.
I mean,
dmesg | raffaello <arguments>.

I think it will be useful once i forgot use raffaello.

**Comment by clobrano** [comment]
Hi,

at the current development phase, pipes are not supported, but I already had the intention to do something about that.

**Comment by clobrano** [comment]
Hi,

pipe is now supported in Raffaello version 1.2.0

regards
