### ISSUE TITLE
distribute raffaello via PyPI

### ISSUE THREAD

**Issue by boegel** [clobrano/raffaello#2]
Any particular reason raffaello isn't available via PyPI (https://pypi.python.org) yet?

This looks very interesting to integrate into EasyBuild (http://hpcugent.github.io/easybuild), where we deal with huge blobs of command output all the time.

**Comment by clobrano** [comment]
Hi!
actually no reason at all. I just registered the package to PyPI, let me know if I can help somehow

**Comment by clobrano** [comment]
Hi boegel,

if that's ok for you, I would close this issue

**Comment by boegel** [comment]
https://pypi.python.org/pypi/raffaello is there no, makes sense, thanks!
